osc_sdk/sdk.py
=> Add OKMS service

osc_sdk/sdk.py
Signed-off-by: abdallah.balti <abdallah.balti@outscale.com>
=> TINA-5438 Added scality support

readme.md
Un oubli vis a vis du changement de dossier de conf
=> TINA-6267 Update README with new configuration folder

osc_sdk/sdk.py, requirements.txt
=> Fix Bandit warning (B314:blacklist)

readme.md, windows-setup.md
=> doc: add some help for windows users

README.md, osc_sdk/sdk.py
Clean dead code and basic refactoring
=> Cleaning & Refactoring

.github/workflows/auto-build.yml, .github/workflows/code-check.yml
=> ci: fix documentation and job naming

CONTRIBUTING.md, osc_sdk/sdk.py, tests/generic_tests/01_auth_access_key.sh, tests/generic_tests/02_auth_bad.sh, tests/generic_tests/03_auth_password.sh
Rework authentication options
- share password authentication along all classes (not only Icu)
- make --authentication-metod an explicit option (with --help)
- make --login and --password an explicit option (with --help)
- command line options superseed profile options
- add option sanity check
=> Rework auth options

pkg/Makefile
=> Update AppImage building with python 3.9.7

CONTRIBUTING.md
=> Add release documentation

pkg/Makefile, pkg/configure
Signed-off-by: Matthias Gatto <matthias.gatto@outscale.com>
=> pkg: rework appimage build to automatically fetch last minor version

pkg/Makefile, pkg/configure
small improvements to pkg build:
- enable to optionally use sudo with docker 
- auto create config.mk if ./configure hasn't been called before
=> Rework pkg make

.github/workflows/pull-request.yml, Makefile
No need to run configure anymore in this context.
=> Update packaging invocation

CONTRIBUTING.md
=> Update release documentation

.github/workflows/release.yml, Makefile
=> Fix pypi upload from github actions

.github/workflows/pull-request.yml
=> ci: auto-merge dependabot if all tests are ok

.github/workflows/pull-request.yml, .pre-commit-config.yaml, osc_sdk/sdk.py, osc_sdk/test_noauth.py, tests/generic_tests/04_auth_none.sh, tests/test_pytest.sh
=> Fix non auth calls

osc_sdk/sdk.py, setup.py
=> osc-cli v1.8.0

README.md
Update documentation about osc-cli installation
=> Update documentation about installation on various OS

osc_sdk/sdk.py
fix #209
Signed-off-by: Matthias Gatto <matthias.gatto@outscale.com>
=> Icu: fix call not working by default

setup.py
Signed-off-by: Matthias Gatto <matthias.gatto@outscale.com>
=> fix bash-completion installation with setuptool

.github/workflows/pull-request.yml, tests/generic_tests/00_one_call_per_service.sh, tests/generic_tests/01_auth_access_key.sh, tests/generic_tests/02_auth_bad.sh, tests/generic_tests/03_auth_password.sh, tests/generic_tests/04_auth_none.sh, tests/generic_tests/common_functions.sh
=> Integration tests in CI

windows-setup.md
=> Fix windows documentation

README.md, osc_sdk/sdk.py
=> Add --version option

osc_sdk/sdk.py, setup.py
=> osc-cli v1.10.0

.github/workflows/pull-local-request.yml, local_tests.sh, osc_sdk/sdk.py, tests/generic_tests/00_one_call_per_service.sh, tests/generic_tests/01_auth_access_key.sh, tests/generic_tests/02_auth_bad.sh, tests/generic_tests/03_auth_password.sh, tests/generic_tests/04_auth_none.sh
=> Local test
